ALTER TABLE users ADD COLUMN energy INTEGER DEFAULT 10;
ALTER TABLE users ADD COLUMN boosts_today INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN spins_today INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN energy_reset_date TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN spin_reset_date TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN challenges_today INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN challenges_reset_date TEXT DEFAULT '';
